# Generated by Django 4.0.4 on 2022-05-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountUser',
        ),
    ]
